baseURL = 'https://seismobassoon.github.io/seismobassoon/'

theme = "PaperMod"
title = 'Nobuaki Fuji'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

languageCode = 'en'

disablePathToLower = false

[params]
    displayFullLangName = true
    ShowReadingTime = false
    ShowBreadCrumbs = false
    ShowPostNavLinks = false
    [params.assets]
        customCSS = ["css/custom.css"]

    [params.profileMode]
        enabled = true
        title = "Nobuaki Fuji"
        subtitle = "Geophysics â€¢ Art & Science"
        imageUrl = "images/moi.png"
        imageWidth = 180
        imageHeight = 160
    

    [[params.socialIcons]]
        name = "googlescholar"
        url = "https://scholar.google.com/citations?user=EqiISYkAAAAJ"

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/nobuaki-fuji-82ba9520"

    [[params.socialIcons]]
        name = "youtube"
        url = "https://www.youtube.com/@seismobassoon"


[languages]

  [languages.en]
    weight = 1
    languageName = "English"
    languageCode = "EN"
    contentDir = "content/en"
    [[languages.en.menu.main]]
        name = "About"
        url = "about/"
        weight = 1
    [[languages.en.menu.main]]
        name = "About"
        url = "cv/"
        weight = 2
    [[languages.en.menu.main]]
        name = "Team"
        url = "team/"
        weight = 3
    [[languages.en.menu.main]]
        name = "Research"
        url = "research/"
        weight = 4
    [[languages.en.menu.main]]
        name = "Education"
        url = "education/"
        weight = 5
    [[languages.en.menu.main]]
        name = "Geomusic"
        url = "geomusic/"
        weight = 6
  [languages.fr]
    weight = 2
    languageName = "FranÃ§ais"
    contentDir = "content/fr"
    [[languages.fr.menu.main]]
        name = "ğŸ“¢"
        url = "news/"
        weight = 1
    [[languages.fr.menu.main]]
        name = "ğŸ‘¤"
        url = "cv/"
        weight = 2
    [[languages.fr.menu.main]]
        name = "ğŸ‘¥"
        url = "team/"
        weight = 3
    [[languages.fr.menu.main]]
        name = "ğŸ§ "
        url = "research/"
        weight = 4
    [[languages.fr.menu.main]]
        name = "ğŸ«"
        url = "education/"
        weight = 5
    [[languages.fr.menu.main]]
        name = "ğŸ¶"
        url = "geomusic/"
        weight = 6
    




    
  [languages.jp]
    weight = 3
    languageName = "æ—¥æœ¬èª"
    contentDir = "content/jp"
    [[languages.jp.menu.main]]
        name = "ã‚ˆã†ã“ã"
        url = "about/"
        weight = 1
    [[languages.jp.menu.main]]
        name = "è·æ­´"
        url = "cv/"
        weight = 2
    [[languages.jp.menu.main]]
        name = "ç ”ç©¶å®¤"
        url = "team/"
        weight = 3
    [[languages.jp.menu.main]]
        name = "ç ”ç©¶"
        url = "research/"
        weight = 4
    [[languages.jp.menu.main]]
        name = "æ•™è‚²"
        url = "education/"
        weight = 5
    [[languages.jp.menu.main]]
        name = "ã‚¸ã‚ªéŸ³æ¥½"
        url = "geomusic/"
        weight = 6
    


  [languages.de]
    weight = 4
    languageName = "Deutsch"
    contentDir = "content/de"
