baseURL = 'https://seismobassoon.github.io/seismobassoon/'

theme = "PaperMod"
title = 'Nobuaki Fuji'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

languageCode = 'en'

disablePathToLower = false

[params]
    displayFullLangName = true


    [params.profileMode]
        enabled = true
        title = "Nobuaki Fuji"
        subtitle = "Geophysics • Art & Science"
        imageUrl = "images/moi.png"
        imageWidth = 180
        imageHeight = 160
    

    [[params.socialIcons]]
        name = "googlescholar"
        url = "https://scholar.google.com/citations?user=EqiISYkAAAAJ"

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/nobuaki-fuji-82ba9520"

    [[params.socialIcons]]
        name = "youtube"
        url = "https://www.youtube.com/@seismobassoon"


[languages]

  [languages.en]
    weight = 1
    languageName = "English"
    languageCode = "EN"
    contentDir = "content/en"
    [[languages.en.menu.main]]
        name = "About"
        url = "about/"
        weight = 1
    [[languages.en.menu.main]]
        name = "CV"
        url = "cv/"
        weight = 2
    [[languages.en.menu.main]]
        name = "Team"
        url = "team/"
        weight = 3
    [[languages.en.menu.main]]
        name = "Research"
        url = "research/"
        weight = 4
    [[languages.en.menu.main]]
        name = "Education"
        url = "education/"
        weight = 5
    [[languages.en.menu.main]]
        name = "Bassoon"
        url = "bassoon/"
        weight = 6
    [[languages.en.menu.main]]
        name = "Composition"
        url = "composition/"
        weight = 7
  [languages.fr]
    weight = 2
    languageName = "Français"
    contentDir = "content/fr"
    [[languages.fr.menu.main]]
        name = "Enchanté"
        url = "about/"
        weight = 1
    [[languages.fr.menu.main]]
        name = "Parcours"
        url = "cv/"
        weight = 2
    [[languages.fr.menu.main]]
        name = "Équipe"
        url = "team/"
        weight = 3
    [[languages.fr.menu.main]]
        name = "Recherche"
        url = "research/"
        weight = 4
    [[languages.fr.menu.main]]
        name = "Enseignement"
        url = "education/"
        weight = 5
    [[languages.fr.menu.main]]
        name = "Basson"
        url = "bassoon/"
        weight = 6
    [[languages.fr.menu.main]]
        name = "Composition"
        url = "composition/"
        weight = 7




    
  [languages.jp]
    weight = 3
    languageName = "日本語"
    contentDir = "content/jp"

  [languages.de]
    weight = 4
    languageName = "Deutsch"
    contentDir = "content/de"
