baseURL = 'https://seismobassoon.github.io/'

theme = "PaperMod"
title = 'Nobuaki Fuji'
  
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
languageCode = 'en'




disablePathToLower = false


[params]
    displayFullLangName = false
    ShowReadingTime = false
    ShowBreadCrumbs = false
    ShowPostNavLinks = false
    googleSiteVerification = "YxiAZLMcK1ogVJx0r_32wyQ2IGTOVBJBA9tbF-y0piY"
    [params.analytics.google]
          SiteVerificationTag = "YxiAZLMcK1ogVJx0r_32wyQ2IGTOVBJBA9tbF-y0piY"

    [params.assets]
        customCSS = ["css/custom.css"]

    [params.profileMode]
        enabled = true
        title = "Nobuaki Fuji"
        subtitle = "Geophysics â€¢ Art & Science"
        imageUrl = "images/moi.png"
        imageWidth = 180
        imageHeight = 160
    

    [[params.socialIcons]]
        name = "googlescholar"
        url = "https://scholar.google.com/citations?user=EqiISYkAAAAJ"

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/nobuaki-fuji-82ba9520"

    [[params.socialIcons]]
        name = "youtube"
        url = "https://www.youtube.com/@seismobassoon"


    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/seismobassoon"

[languages]

  [languages.en]
    weight = 1
    languageName ="English"
    languageCode = "en"
    contentDir = "content/en"
    [languages.en.params]
      langBadge = "EN"
      
    [[languages.en.menu.main]]
        name = "ğŸ“¢"
        pre = "News"
        url = "news/"
        weight = 1
    [[languages.en.menu.main]]
        name = "ğŸ‘¤"
        pre = "About"
        url = "cv/"
        weight = 2
    [[languages.en.menu.main]]
        name = "ğŸ‘¥"
        pre = "Team"
        url = "team/"
        weight = 3
    [[languages.en.menu.main]]
        name = "ğŸ§ "
        pre = "Research"
        url = "research/"
        weight = 4
    [[languages.en.menu.main]]
        name = "ğŸ«"
        pre = "Education"
        url = "education/"
        weight = 5
    [[languages.en.menu.main]]
        name = "ğŸ¹"
        pre = "PhiloGaÃ¯a"
        url = "geomusic/"
        weight = 6

        
  [languages.fr]
    weight = 2
    languageName = "FranÃ§ais"
    contentDir = "content/fr"
    [languages.fr.params]
      langBadge = "FR"
    [[languages.fr.menu.main]]
        name = "ğŸ“¢"
        pre = "actu"
        url = "news/"
        weight = 1
    [[languages.fr.menu.main]]
        name = "ğŸ‘¤"
        pre = "moi"
        url = "cv/"
        weight = 2
    [[languages.fr.menu.main]]
        name = "ğŸ‘¥"
        pre = "Ã©quipe"
        url = "team/"
        weight = 3
    [[languages.fr.menu.main]]
        name = "ğŸ§ "
        pre = "recherche"
        url = "research/"
        weight = 4
    [[languages.fr.menu.main]]
        name = "ğŸ«"
        pre = "enseignement"
        url = "education/"
        weight = 5
    [[languages.fr.menu.main]]
        name = "ğŸ¹"
        pre = "philogaÃ¯a"
        url = "geomusic/"
        weight = 6
    




    
  [languages.jp]
    weight = 3
    languageName = "æ—¥æœ¬èª"
    contentDir = "content/jp"
    [languages.jp.params]
      langBadge = "ã‚"
    [[languages.jp.menu.main]]
        name = "ğŸ“¢"
        pre = "ãƒ‹ãƒ¥ãƒ¼ã‚¹"
        url = "news/"
        weight = 1
    [[languages.jp.menu.main]]
        name = "ğŸ‘¤"
        pre = "ç§"
        url = "cv/"
        weight = 2
    [[languages.jp.menu.main]]
        name = "ğŸ‘¥"
        pre = "ç ”ç©¶å®¤"
        url = "team/"
        weight = 3
    [[languages.jp.menu.main]]
        name = "ğŸ§ "
        pre = "ç ”ç©¶"
        url = "research/"
        weight = 4
    [[languages.jp.menu.main]]
        name = "ğŸ«"
        pre = "æ•™è‚²"
        url = "education/"
        weight = 5
    [[languages.jp.menu.main]]
        name = "ğŸ¹"
        pre = "ãƒ•ã‚£ãƒ­ã‚¬ã‚¤ã‚¢"
        url = "geomusic/"
        weight = 6




  [languages.de]
  weight = 4
  languageName = "Deutsch"
  contentDir = "content/de"
  [languages.de.params]
    langBadge = "DE"

  [[languages.de.menu.main]]
      name = "ğŸ“¢"
      pre = "Aktuelles"
      url = "news/"
      weight = 1

  [[languages.de.menu.main]]
      name = "ğŸ‘¤"
      pre = "Ãœber mich"
      url = "cv/"
      weight = 2

  [[languages.de.menu.main]]
      name = "ğŸ‘¥"
      pre = "Team"
      url = "team/"
      weight = 3

  [[languages.de.menu.main]]
      name = "ğŸ§ "
      pre = "Forschung"
      url = "research/"
      weight = 4

  [[languages.de.menu.main]]
      name = "ğŸ«"
      pre = "Lehre"
      url = "education/"
      weight = 5

  [[languages.de.menu.main]]
      name = "ğŸ¹"
      pre = "Philogaia"
      url = "geomusic/"
      weight = 6

   
    
  [languages.no]
    weight = 5
    languageName = "BokmÃ¥l"
    contentDir = "content/no"
    [languages.no.params]
      langBadge = "NO"
    [[languages.no.menu.main]]
        name = "ğŸ“¢"
        pre = "Nyheter"
        url = "news/"
        weight = 1
    [[languages.no.menu.main]]
        name = "ğŸ‘¤"
        pre = "Meg"
        url = "cv/"
        weight = 2
    [[languages.no.menu.main]]
        name = "ğŸ‘¥"
        pre = "Gruppe"
        url = "team/"
        weight = 3
    [[languages.no.menu.main]]
        name = "ğŸ§ "
        pre = "Forskning"
        url = "research/"
        weight = 4
    [[languages.no.menu.main]]
        name = "ğŸ«"
        pre = "Undervisning"
        url = "education/"
        weight = 5
    [[languages.no.menu.main]]
        name = "ğŸ¹"
        pre = "PhiloGaÃ¯a"
        url = "geomusic/"
        weight = 6
